Alias: $vaccinetype = http://smart.who.int/pcmt-vaxprequal/CodeSystem/PreQualVaccineType
CodeSystem: PreQualVaccineType
Title : "WHO PreQualificaiton Vaccine VaccineTypes"
Description: "WHO PreQualificaiton Vaccine VaccineTypes"

* #BCG "BCG"
* #DT "DT"
* #DTwP "DTwP"
* #HepA "HepA"
* #HepB "HepB"
* #JE "JE"
* #LARV "LARV"
* #M "M"
* #MMR "MMR"
* #MR "MR"
* #Malaria "Malaria"
* #TDV "TDV"
* #TT "TT"
* #YF "YF"
* #bOPV "bOPV"
* #dT "dT"
* #tOPV "tOPV"
